version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: apps/scraper/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HOST=0.0.0.0
    depends_on:
      - redis
    networks:
      - app-network
    ports:
      - "3000:3000"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data: 